ARG python_ver=3.12
FROM python:${python_ver}

ARG netbox_ver={{ netbox_version }}
ENV PYTHONUNBUFFERED 1

RUN mkdir -p /opt

RUN pip install --upgrade pip

# -------------------------------------------------------------------------------------
# Install NetBox
# -------------------------------------------------------------------------------------
RUN git clone --single-branch --branch ${netbox_ver} https://github.com/netbox-community/netbox.git /opt/netbox/ && \
    cd /opt/netbox/ && \
    pip install -r /opt/netbox/requirements.txt

# -------------------------------------------------------------------------------------
# Install Netbox Plugin
# -------------------------------------------------------------------------------------
RUN mkdir -p /source
WORKDIR /source
COPY . /source

#RUN pip install -r requirements.txt
{% if install_method =="g" %}
RUN python -m pip install --editable .
{% else %}
RUN python -m pip install {{ netbox_plugin }}
{% endif %}
{% if netbox_branching %}
RUN python -m pip install netboxlabs-netbox-branching
{% endif %}
WORKDIR /opt/netbox/netbox/
