---
services:
  netbox:
    build:
      context: ../
      dockerfile: docker-develop-floorplan/Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_floorplan:/source/netbox_floorplan
    tty: true
  worker:
    build:
      context: ../
      dockerfile: docker-develop-floorplan/Dockerfile
    command: sh -c "python manage.py rqworker"
    depends_on:
      - netbox
    env_file:
      - ./dev.env
    volumes:
      - ./configuration.py:/opt/netbox/netbox/netbox/configuration.py
      - ../netbox_floorplan:/source/netbox_floorplan
    tty: true
  postgres:
    image: postgres:16
    env_file: dev.env
    volumes:     
      - pgdata_netbox_floorplan:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    command:
      - sh
      - -c  # this is to evaluate the $REDIS_PASSWORD from the env
      - redis-server --appendonly yes --requirepass $$REDIS_PASSWORD  ## $$ because of docker-compose
    env_file: ./dev.env
volumes:
  pgdata_netbox_floorplan:
